version: '3.1'
services:
  web:
    image: odoo:17.0
    container_name: odoo
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - TZ=Asia/Shanghai
      - PASSWORD_FILE=/run/secrets/postgresql_password
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./odoo-web-log:/var/log/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    secrets:
      - postgresql_password
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

volumes:
  odoo-web-data:
  odoo-db-data:
  
secrets:
  postgresql_password:
    file: odoo_pg_pass